--------------------------------------------------------
-- Archivo creado  - domingo-noviembre-18-2018   
--------------------------------------------------------
DROP TABLE "UBERDBA"."AÑO";
DROP TABLE "UBERDBA"."CLIENTE";
DROP TABLE "UBERDBA"."CODIGO_PROMOCIONAL";
DROP TABLE "UBERDBA"."CONDUCTOR";
DROP TABLE "UBERDBA"."CONDUCTOR_VEHICULO";
DROP TABLE "UBERDBA"."DATALLE_METODO_DE_PAGO";
DROP TABLE "UBERDBA"."DETALLE_CODIGO_PROMOCIONAL";
DROP TABLE "UBERDBA"."DETALLE_FACTURA";
DROP TABLE "UBERDBA"."DETALLE_RECORRIDO";
DROP TABLE "UBERDBA"."DETALLE_SERVICIO";
DROP TABLE "UBERDBA"."DETALLE_VEHICULO";
DROP TABLE "UBERDBA"."ENTIDAD_DE_PAGO";
DROP TABLE "UBERDBA"."ESTADO_DE_SERVICIO";
DROP TABLE "UBERDBA"."FACTURA";
DROP TABLE "UBERDBA"."GEOGRAFIA";
DROP TABLE "UBERDBA"."LENGUAJE";
DROP TABLE "UBERDBA"."LIQUIDACION";
DROP TABLE "UBERDBA"."MARCA";
DROP TABLE "UBERDBA"."METODO_DE_PAGO";
DROP TABLE "UBERDBA"."MODELO";
DROP TABLE "UBERDBA"."MONEDA";
DROP TABLE "UBERDBA"."REPORTE_PAGO_DETALLE";
DROP TABLE "UBERDBA"."SERVICIO";
DROP TABLE "UBERDBA"."TIPO_DOCUMENTO";
DROP TABLE "UBERDBA"."TIPO_MEDIO_DE_PAGO";
DROP TABLE "UBERDBA"."TIPO_VEHICULO";
DROP TABLE "UBERDBA"."VEHICULO";
DROP VIEW "UBERDBA"."MEDIOS_PAGO_CLIENTES";
DROP VIEW "UBERDBA"."VIAJES_CLIENTES";
DROP PROCEDURE "UBERDBA"."CALCULAR_TARIFA";
DROP FUNCTION "UBERDBA"."VALOR_DISTANCIA";
DROP FUNCTION "UBERDBA"."VALOR_TIEMPO";
DROP SYNONYM "PUBLIC"."DBMS_OUTPUT";
--------------------------------------------------------
--  DDL for Table AÑO
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."AÑO" 
   (	"ID_AÑO" NUMBER(*,0), 
	"DESCRIPCIONAÑO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER(*,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"LAST_NAME" VARCHAR2(255 BYTE), 
	"PROFILE_PHOTO" VARCHAR2(255 BYTE), 
	"ID_LENGUAJE" NUMBER(*,0), 
	"EMAIL_ADRESS" VARCHAR2(255 BYTE), 
	"EMAIL_ADRESS_2" VARCHAR2(255 BYTE), 
	"MOBILE" VARCHAR2(255 BYTE), 
	"ID_GEOGRAFIA" NUMBER(*,0), 
	"INVITE_CODE" VARCHAR2(255 BYTE), 
	"ID_TIPODOCUMENTO" VARCHAR2(255 BYTE), 
	"SERVICIO_EMPRESARIAL" NUMBER, 
	"NOMBRE_EMPRESA" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table CODIGO_PROMOCIONAL
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."CODIGO_PROMOCIONAL" 
   (	"ID_CODIGOPROMOCIONAL" NUMBER(*,0), 
	"DESCRIPCION_CODIGO" VARCHAR2(255 BYTE), 
	"ID_CLIENTE" NUMBER(*,0), 
	"FECHAASIGNACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table CONDUCTOR
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."CONDUCTOR" 
   (	"ID_CONDUCTOR" NUMBER(*,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"LAST_NAME" VARCHAR2(255 BYTE), 
	"PROFILE_PHOTO" VARCHAR2(255 BYTE), 
	"ID_LENGUAJE" NUMBER(*,0), 
	"EMAIL_ADRESS" VARCHAR2(255 BYTE), 
	"EMAIL_ADRESS_2" VARCHAR2(255 BYTE), 
	"MOBILE" VARCHAR2(255 BYTE), 
	"ID_GEOGRAFIA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table CONDUCTOR_VEHICULO
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."CONDUCTOR_VEHICULO" 
   (	"ID_CONDUCTORVEHICULO" NUMBER(*,0), 
	"ID_CONDUCTOR" NUMBER(*,0), 
	"ID_VEHICULO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table DATALLE_METODO_DE_PAGO
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."DATALLE_METODO_DE_PAGO" 
   (	"ID_DETALLEMETODOPAGO" NUMBER(*,0), 
	"ID_METODOPAGO" NUMBER(*,0), 
	"TIPOMEDIOPAGO" VARCHAR2(255 BYTE), 
	"NUMEROTARJETA" VARCHAR2(255 BYTE), 
	"CODIGOSEGURIDADTARJETA" VARCHAR2(255 BYTE), 
	"FECHAVENCIMIENTOTARJETA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table DETALLE_CODIGO_PROMOCIONAL
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."DETALLE_CODIGO_PROMOCIONAL" 
   (	"ID_DETALLECODIGOPROMOCIONAL" NUMBER(*,0), 
	"ID_CODIGOPROMOCIONAL" NUMBER(*,0), 
	"VALOR_CODIGO" VARCHAR2(255 BYTE), 
	"ESTADOCODIGO" VARCHAR2(255 BYTE), 
	"FECHAREDENCION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table DETALLE_FACTURA
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."DETALLE_FACTURA" 
   (	"ID_DETALLEFACTURA" NUMBER(*,0), 
	"ID_FACTURA" NUMBER(*,0), 
	"DETALLE_FACTURA" VARCHAR2(255 BYTE), 
	"VALOR" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table DETALLE_RECORRIDO
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."DETALLE_RECORRIDO" 
   (	"ID_DETALLERECORRIDO" NUMBER(*,0), 
	"LONGITUD" VARCHAR2(255 BYTE), 
	"LATITUD" VARCHAR2(255 BYTE), 
	"FECHA_HORA" DATE, 
	"ID_DETALLE_SERVICIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table DETALLE_SERVICIO
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."DETALLE_SERVICIO" 
   (	"ID_DETALLESERVICIO" NUMBER(*,0), 
	"TIPO_TARIFA" NUMBER(*,0), 
	"MEDIOPAGO" VARCHAR2(255 BYTE), 
	"TIEMPOTOTAL" VARCHAR2(255 BYTE), 
	"RECORRIDO" VARCHAR2(255 BYTE), 
	"ID_SERVICIO" NUMBER, 
	"TOTAL_SERVICIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table DETALLE_VEHICULO
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."DETALLE_VEHICULO" 
   (	"ID_DETALLEVEHICULO" NUMBER(*,0), 
	"ID_VEHICULO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table ENTIDAD_DE_PAGO
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."ENTIDAD_DE_PAGO" 
   (	"ID_ENTIDADPAGO" NUMBER(*,0), 
	"DESCRIPCIONENTIDADPAGO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table ESTADO_DE_SERVICIO
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."ESTADO_DE_SERVICIO" 
   (	"ID_ESTADOSERVICIO" NUMBER(*,0), 
	"DESCRIPCIONESTADOSERVICIO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table FACTURA
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."FACTURA" 
   (	"ID_FACTURA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table GEOGRAFIA
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."GEOGRAFIA" 
   (	"ID_GEOGRAFIA" NUMBER(*,0), 
	"DEPARTAMENTO" VARCHAR2(255 BYTE), 
	"PAIS" VARCHAR2(255 BYTE), 
	"CIUDAD" VARCHAR2(255 BYTE), 
	"VALOR_KILOMETRO" NUMBER, 
	"VALOR_MINUTO" NUMBER, 
	"TARIFA_BASE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table LENGUAJE
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."LENGUAJE" 
   (	"ID_LENGUAJE" NUMBER(*,0), 
	"DESCRIPCION_LENGUAJE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table LIQUIDACION
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."LIQUIDACION" 
   (	"ID_LIQUIDACION" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table MARCA
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."MARCA" 
   (	"ID_MARCA" NUMBER(*,0), 
	"DESCRIPCIONMARCA" VARCHAR2(255 BYTE), 
	"ID_MODELO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table METODO_DE_PAGO
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."METODO_DE_PAGO" 
   (	"ID_METODOPAGO" NUMBER(*,0), 
	"DESCRIPCIONMETODOPAGO" VARCHAR2(255 BYTE), 
	"ID_CLIENTE" NUMBER, 
	"ID_TIPO_MEDIO_DE_PAGO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table MODELO
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."MODELO" 
   (	"ID_MODELO" NUMBER(*,0), 
	"DESCRIPCIONMODELO" VARCHAR2(255 BYTE), 
	"ID_AÑO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table MONEDA
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."MONEDA" 
   (	"ID_MONEDA" NUMBER(*,0), 
	"DESCRIPCION_MONEDA" VARCHAR2(255 BYTE), 
	"VALOR" NUMBER(*,0), 
	"ID_GEOGRAFIA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table REPORTE_PAGO_DETALLE
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."REPORTE_PAGO_DETALLE" 
   (	"ID_REPORTEPAGODETALLE" NUMBER(*,0), 
	"ID_ENTIDADPAGO" NUMBER(*,0), 
	"FECHAPAGO" DATE, 
	"VALORPAGO" NUMBER(*,0), 
	"DESCRIPCIONPAGO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table SERVICIO
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."SERVICIO" 
   (	"ID_SERVICIO" NUMBER(*,0), 
	"FECHASERVICIO" DATE, 
	"ID_CONDUCTORVEHICULO" NUMBER, 
	"ID_GEOGRAFIA" NUMBER, 
	"ID_ESTADOSERVICIO" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table TIPO_DOCUMENTO
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."TIPO_DOCUMENTO" 
   (	"ID_TIPODOCUMENTO" NUMBER(*,0), 
	"DESCRIPCIONDOCUMENTO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table TIPO_MEDIO_DE_PAGO
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."TIPO_MEDIO_DE_PAGO" 
   (	"ID_TIPO_MEDIO_DE_PAGO" NUMBER(*,0), 
	"DESCRIPCION_TIPO_MEDIO_DE_PAGO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table TIPO_VEHICULO
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."TIPO_VEHICULO" 
   (	"ID_TIPOVEHICULO" NUMBER(*,0), 
	"DESCRIPCIONTIPOVEHICULO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Table VEHICULO
--------------------------------------------------------

  CREATE TABLE "UBERDBA"."VEHICULO" 
   (	"ID_VEHICULO" NUMBER(*,0), 
	"PLACA" VARCHAR2(255 BYTE), 
	"ID_MARCA" NUMBER(*,0), 
	"DESCRIPCIONVEHICULO" VARCHAR2(255 BYTE), 
	"ID_TIPO_VEHICULO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for View MEDIOS_PAGO_CLIENTES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "UBERDBA"."MEDIOS_PAGO_CLIENTES" ("ID_CLIENTE", "NOMBRE_CLIENTE", "ID_TIPO_MEDIO_DE_PAGO", "DESCRIPCION_TIPO_MEDIO_DE_PAGO", "DESCRIPCIONMETODOPAGO", "SERVICIO_EMPRESARIAL", "NOMBRE_EMPRESA") AS 
  SELECT A.ID_CLIENTE, A.NAME || A.LAST_NAME AS NOMBRE_CLIENTE, C.ID_TIPO_MEDIO_DE_PAGO, C.Descripcion_TIPO_MEDIO_DE_PAGO, B.DESCRIPCIONMETODOPAGO, 
A.SERVICIO_EMPRESARIAL, A.NOMBRE_EMPRESA
FROM CLIENTE A
LEFT JOIN METODO_DE_PAGO B ON A.ID_CLIENTE = B.ID_CLIENTE
LEFT JOIN TIPO_MEDIO_DE_PAGO C ON B.ID_TIPO_MEDIO_DE_PAGO = C.ID_TIPO_MEDIO_DE_PAGO
;
--------------------------------------------------------
--  DDL for View VIAJES_CLIENTES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "UBERDBA"."VIAJES_CLIENTES" ("FECHA_VIAJE", "NOMBRE_CONDUCTOR", "PLACA_VEHICULO", "NOMBRE_CLIENTE", "VALOR_TOTAL", "TARIFA_DINAMICA", "TIPO_SERVICIO", "CIUDAD_VIAJE") AS 
  SELECT A.FECHASERVICIO AS FECHA_VIAJE, B.NAME || B.LAST_NAME AS NOMBRE_CONDUCTOR, 
G.PLACA AS PLACA_VEHICULO, C.NAME || C.LAST_NAME AS NOMBRE_CLIENTE, D.TOTAL_SERVICIO AS VALOR_TOTAL,
CASE WHEN TIPO_TARIFA = 1 THEN 'TRUE' ELSE 'FALSE' END AS TARIFA_DINAMICA,
H.DESCRIPCIONTIPOVEHICULO AS TIPO_SERVICIO, E.CIUDAD AS CIUDAD_VIAJE
FROM SERVICIO A
INNER JOIN CLIENTE C ON A.ID_CLIENTE = C.ID_CLIENTE
INNER JOIN DETALLE_SERVICIO D ON A.ID_SERVICIO = D.ID_SERVICIO
INNER JOIN GEOGRAFIA E ON A.ID_GEOGRAFIA = E.ID_GEOGRAFIA
INNER JOIN CONDUCTOR_VEHICULO F ON A.ID_CONDUCTORVEHICULO = F.ID_CONDUCTORVEHICULO
INNER JOIN CONDUCTOR B ON B.ID_CONDUCTOR = F.ID_CONDUCTOR
INNER JOIN VEHICULO G ON G.ID_VEHICULO = F.ID_VEHICULO
INNER JOIN TIPO_VEHICULO H ON G.ID_TIPO_VEHICULO = H.ID_TIPOVEHICULO
;
REM INSERTING into UBERDBA."AÑO"
SET DEFINE OFF;
REM INSERTING into UBERDBA.CLIENTE
SET DEFINE OFF;
REM INSERTING into UBERDBA.CODIGO_PROMOCIONAL
SET DEFINE OFF;
REM INSERTING into UBERDBA.CONDUCTOR
SET DEFINE OFF;
REM INSERTING into UBERDBA.CONDUCTOR_VEHICULO
SET DEFINE OFF;
REM INSERTING into UBERDBA.DATALLE_METODO_DE_PAGO
SET DEFINE OFF;
REM INSERTING into UBERDBA.DETALLE_CODIGO_PROMOCIONAL
SET DEFINE OFF;
REM INSERTING into UBERDBA.DETALLE_FACTURA
SET DEFINE OFF;
REM INSERTING into UBERDBA.DETALLE_RECORRIDO
SET DEFINE OFF;
REM INSERTING into UBERDBA.DETALLE_SERVICIO
SET DEFINE OFF;
REM INSERTING into UBERDBA.DETALLE_VEHICULO
SET DEFINE OFF;
REM INSERTING into UBERDBA.ENTIDAD_DE_PAGO
SET DEFINE OFF;
REM INSERTING into UBERDBA.ESTADO_DE_SERVICIO
SET DEFINE OFF;
REM INSERTING into UBERDBA.FACTURA
SET DEFINE OFF;
REM INSERTING into UBERDBA.GEOGRAFIA
SET DEFINE OFF;
REM INSERTING into UBERDBA.LENGUAJE
SET DEFINE OFF;
REM INSERTING into UBERDBA.LIQUIDACION
SET DEFINE OFF;
REM INSERTING into UBERDBA.MARCA
SET DEFINE OFF;
REM INSERTING into UBERDBA.METODO_DE_PAGO
SET DEFINE OFF;
REM INSERTING into UBERDBA.MODELO
SET DEFINE OFF;
REM INSERTING into UBERDBA.MONEDA
SET DEFINE OFF;
REM INSERTING into UBERDBA.REPORTE_PAGO_DETALLE
SET DEFINE OFF;
REM INSERTING into UBERDBA.SERVICIO
SET DEFINE OFF;
REM INSERTING into UBERDBA.TIPO_DOCUMENTO
SET DEFINE OFF;
REM INSERTING into UBERDBA.TIPO_MEDIO_DE_PAGO
SET DEFINE OFF;
REM INSERTING into UBERDBA.TIPO_VEHICULO
SET DEFINE OFF;
REM INSERTING into UBERDBA.VEHICULO
SET DEFINE OFF;
REM INSERTING into UBERDBA.MEDIOS_PAGO_CLIENTES
SET DEFINE OFF;
REM INSERTING into UBERDBA.VIAJES_CLIENTES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index AÑO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."AÑO_PK" ON "UBERDBA"."AÑO" ("ID_AÑO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."CLIENTE_PK" ON "UBERDBA"."CLIENTE" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index CODIGO_PROMOCIONAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."CODIGO_PROMOCIONAL_PK" ON "UBERDBA"."CODIGO_PROMOCIONAL" ("ID_CODIGOPROMOCIONAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index CONDUCTOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."CONDUCTOR_PK" ON "UBERDBA"."CONDUCTOR" ("ID_CONDUCTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index DATALLE_METODO_DE_PAGO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."DATALLE_METODO_DE_PAGO_PK" ON "UBERDBA"."DATALLE_METODO_DE_PAGO" ("ID_DETALLEMETODOPAGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index DETALLE_CODIGO_PROMOCIONAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."DETALLE_CODIGO_PROMOCIONAL_PK" ON "UBERDBA"."DETALLE_CODIGO_PROMOCIONAL" ("ID_DETALLECODIGOPROMOCIONAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index GEOGRAFIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."GEOGRAFIA_PK" ON "UBERDBA"."GEOGRAFIA" ("ID_GEOGRAFIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index ID_CONDUCTORVEHICULO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."ID_CONDUCTORVEHICULO_PK" ON "UBERDBA"."CONDUCTOR_VEHICULO" ("ID_CONDUCTORVEHICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index ID_DETALLEFACTURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."ID_DETALLEFACTURA_PK" ON "UBERDBA"."DETALLE_FACTURA" ("ID_DETALLEFACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index ID_DETALLERECORRIDO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."ID_DETALLERECORRIDO_PK" ON "UBERDBA"."DETALLE_RECORRIDO" ("ID_DETALLERECORRIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index ID_DETALLESERVICIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."ID_DETALLESERVICIO_PK" ON "UBERDBA"."DETALLE_SERVICIO" ("ID_DETALLESERVICIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index ID_DETALLEVEHICULO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."ID_DETALLEVEHICULO_PK" ON "UBERDBA"."DETALLE_VEHICULO" ("ID_DETALLEVEHICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index ID_ENTIDADPAGO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."ID_ENTIDADPAGO_PK" ON "UBERDBA"."ENTIDAD_DE_PAGO" ("ID_ENTIDADPAGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index ID_ESTADOSERVICIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."ID_ESTADOSERVICIO_PK" ON "UBERDBA"."ESTADO_DE_SERVICIO" ("ID_ESTADOSERVICIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index ID_FACTURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."ID_FACTURA_PK" ON "UBERDBA"."FACTURA" ("ID_FACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index ID_LIQUIDACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."ID_LIQUIDACION_PK" ON "UBERDBA"."LIQUIDACION" ("ID_LIQUIDACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index ID_REPORTEPAGODETALLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."ID_REPORTEPAGODETALLE_PK" ON "UBERDBA"."REPORTE_PAGO_DETALLE" ("ID_REPORTEPAGODETALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index ID_SERVICIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."ID_SERVICIO_PK" ON "UBERDBA"."SERVICIO" ("ID_SERVICIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index LENGUAJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."LENGUAJE_PK" ON "UBERDBA"."LENGUAJE" ("ID_LENGUAJE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index MARCA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."MARCA_PK" ON "UBERDBA"."MARCA" ("ID_MARCA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index METODO_DE_PAGO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."METODO_DE_PAGO_PK" ON "UBERDBA"."METODO_DE_PAGO" ("ID_METODOPAGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index MODELO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."MODELO_PK" ON "UBERDBA"."MODELO" ("ID_MODELO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index MONEDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."MONEDA_PK" ON "UBERDBA"."MONEDA" ("ID_MONEDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index PROFEAYUDENOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."PROFEAYUDENOS" ON "UBERDBA"."CONDUCTOR_VEHICULO" ("ID_CONDUCTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index PROFEAYUDENOSPORFIS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."PROFEAYUDENOSPORFIS" ON "UBERDBA"."CONDUCTOR_VEHICULO" ("ID_VEHICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index PROFEAYUDENOSPORFIS2
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."PROFEAYUDENOSPORFIS2" ON "UBERDBA"."SERVICIO" ("FECHASERVICIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index TIPO_DOCUMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."TIPO_DOCUMENTO_PK" ON "UBERDBA"."TIPO_DOCUMENTO" ("ID_TIPODOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index TIPO_MEDIO_DE_PAGO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."TIPO_MEDIO_DE_PAGO_PK" ON "UBERDBA"."TIPO_MEDIO_DE_PAGO" ("ID_TIPO_MEDIO_DE_PAGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index TIPO_VEHICULO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."TIPO_VEHICULO_PK" ON "UBERDBA"."TIPO_VEHICULO" ("ID_TIPOVEHICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Index VEHICULO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBERDBA"."VEHICULO_PK" ON "UBERDBA"."VEHICULO" ("ID_VEHICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER" ;
--------------------------------------------------------
--  DDL for Procedure CALCULAR_TARIFA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "UBERDBA"."CALCULAR_TARIFA" (ID_SERVI NUMBER, DISTANCIA_SERVICIO NUMBER, TIEMPO_SERVICIO NUMBER, TOTAL_ADICIONAL NUMBER) AS

ESTADO_SERVICIO VARCHAR(255);
CIUDAD_SERVICIO VARCHAR(255);
TARIFA_BASE1 NUMBER;
VALOR_SERVICIO_DISTANCIA NUMBER;
VALOR_SERVICIO_TIEMPO NUMBER;
VALOR_SERVICIO_TOTAL NUMBER;
VALOR_ADICIONAL NUMBER;

BEGIN

    SELECT I.DESCRIPCIONESTADOSERVICIO ESTADO_VIAJE INTO ESTADO_SERVICIO 
    FROM SERVICIO A
    INNER JOIN DETALLE_SERVICIO D ON A.ID_SERVICIO = D.ID_SERVICIO
    INNER JOIN GEOGRAFIA E ON A.ID_GEOGRAFIA = E.ID_GEOGRAFIA
    INNER JOIN ESTADO_DE_SERVICIO I ON A.ID_ESTADOSERVICIO = I.ID_ESTADOSERVICIO
    WHERE A.ID_SERVICIO = ID_SERVI;
    
    IF ESTADO_SERVICIO = 'REALIZADO' AND DISTANCIA_SERVICIO > 0 THEN
        SELECT E.TARIFA_BASE,E.VALOR_MINUTO, E.VALOR_KILOMETRO ,E.CIUDAD INTO TARIFA_BASE1 ,CIUDAD_SERVICIO 
        FROM SERVICIO A
        INNER JOIN DETALLE_SERVICIO D ON A.ID_SERVICIO = D.ID_SERVICIO
        INNER JOIN GEOGRAFIA E ON A.ID_GEOGRAFIA = E.ID_GEOGRAFIA
        INNER JOIN ESTADO_DE_SERVICIO I ON A.ID_ESTADOSERVICIO = I.ID_ESTADOSERVICIO
        WHERE A.ID_SERVICIO = ID_SERVI;
        
        SELECT VALOR_DISTANCIA( DISTANCIA_SERVICIO, CIUDAD_SERVICIO ) INTO VALOR_SERVICIO_DISTANCIA FROM DUAL;
        SELECT VALOR_TIEMPO( TIEMPO_SERVICIO, CIUDAD_SERVICIO ) INTO VALOR_SERVICIO_TIEMPO FROM DUAL;
        
        VALOR_SERVICIO_TOTAL := VALOR_SERVICIO_DISTANCIA + VALOR_SERVICIO_TIEMPO + TARIFA_BASE1 + VALOR_ADICIONAL;
        
        UPDATE DETALLE_SERVICIO
        SET TOTAL_SERVICIO = VALOR_SERVICIO_TOTAL
        WHERE ID_SERVICIO = (SELECT ID_SERVICIO FROM SERVICIO A WHERE A.ID_SERVICIO = ID_SERVI);
        
        
    ELSE
        UPDATE DETALLE_SERVICIO
        SET TOTAL_SERVICIO = 0
        WHERE ID_SERVICIO = (SELECT ID_SERVICIO FROM SERVICIO A WHERE A.ID_SERVICIO = ID_SERVI);
    END IF;
    
END;/
--------------------------------------------------------
--  DDL for Function VALOR_DISTANCIA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "UBERDBA"."VALOR_DISTANCIA" (DISTANCIA NUMBER, CIUDAD2 VARCHAR) 
    RETURN NUMBER       
IS
VALOR_KILO NUMBER;
CIUDAD3 VARCHAR(255);
MENSAJE_ERROR EXCEPTION;
BEGIN
    SELECT VALOR_KILOMETRO, CIUDAD INTO VALOR_KILO, CIUDAD3 FROM GEOGRAFIA WHERE CIUDAD = CIUDAD2;

    IF DISTANCIA > 0 AND CIUDAD2 = CIUDAD3 THEN
      RETURN (DISTANCIA * VALOR_KILO) ;
    ELSE 
      RAISE MENSAJE_ERROR;
    END IF;

    EXCEPTION
    WHEN MENSAJE_ERROR THEN
         DBMS_OUTPUT.PUT_LINE('La cantidad de distancia y/o la ciudad ingresada es errada, favor validar.');
    RETURN NULL;

END;

/
--------------------------------------------------------
--  DDL for Function VALOR_TIEMPO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "UBERDBA"."VALOR_TIEMPO" (TIEMPO NUMBER, CIUDAD2 VARCHAR) 
    RETURN NUMBER
IS
VALOR_TIMER NUMBER;
CIUDAD3 VARCHAR(255);
MENSAJE_ERROR EXCEPTION;
BEGIN
    SELECT VALOR_MINUTO, CIUDAD  INTO VALOR_TIMER, CIUDAD3 FROM GEOGRAFIA WHERE CIUDAD = CIUDAD2;
    IF TIEMPO > 0 AND CIUDAD2 = CIUDAD3  THEN
      RETURN (TIEMPO * VALOR_TIMER) ;
    ELSE 
      RAISE MENSAJE_ERROR;
    END IF;
    EXCEPTION
    WHEN MENSAJE_ERROR THEN
         DBMS_OUTPUT.PUT_LINE('La cantidad de tiempo y/o la ciudad ingresada es errada, favor validar.');
    RETURN NULL;
END;

/
--------------------------------------------------------
--  DDL for Synonymn DBMS_OUTPUT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PUBLIC SYNONYM "DBMS_OUTPUT" FOR "SYS"."DBMS_OUTPUT";
--------------------------------------------------------
--  Constraints for Table AÑO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."AÑO" ADD CONSTRAINT "AÑO_PK" PRIMARY KEY ("ID_AÑO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."AÑO" MODIFY ("DESCRIPCIONAÑO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."AÑO" MODIFY ("ID_AÑO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."CLIENTE" MODIFY ("NOMBRE_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CLIENTE" MODIFY ("SERVICIO_EMPRESARIAL" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CLIENTE" MODIFY ("ID_TIPODOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."CLIENTE" MODIFY ("INVITE_CODE" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CLIENTE" MODIFY ("ID_GEOGRAFIA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CLIENTE" MODIFY ("MOBILE" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CLIENTE" MODIFY ("EMAIL_ADRESS_2" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CLIENTE" MODIFY ("EMAIL_ADRESS" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CLIENTE" MODIFY ("ID_LENGUAJE" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CLIENTE" MODIFY ("PROFILE_PHOTO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CLIENTE" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CLIENTE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CODIGO_PROMOCIONAL
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."CODIGO_PROMOCIONAL" ADD CONSTRAINT "CODIGO_PROMOCIONAL_PK" PRIMARY KEY ("ID_CODIGOPROMOCIONAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."CODIGO_PROMOCIONAL" MODIFY ("FECHAASIGNACION" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CODIGO_PROMOCIONAL" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CODIGO_PROMOCIONAL" MODIFY ("DESCRIPCION_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CODIGO_PROMOCIONAL" MODIFY ("ID_CODIGOPROMOCIONAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONDUCTOR
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."CONDUCTOR" ADD CONSTRAINT "CONDUCTOR_PK" PRIMARY KEY ("ID_CONDUCTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."CONDUCTOR" MODIFY ("ID_GEOGRAFIA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CONDUCTOR" MODIFY ("MOBILE" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CONDUCTOR" MODIFY ("EMAIL_ADRESS_2" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CONDUCTOR" MODIFY ("EMAIL_ADRESS" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CONDUCTOR" MODIFY ("ID_LENGUAJE" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CONDUCTOR" MODIFY ("PROFILE_PHOTO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CONDUCTOR" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CONDUCTOR" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CONDUCTOR" MODIFY ("ID_CONDUCTOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONDUCTOR_VEHICULO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."CONDUCTOR_VEHICULO" ADD CONSTRAINT "ID_CONDUCTORVEHICULO_PK" PRIMARY KEY ("ID_CONDUCTORVEHICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."CONDUCTOR_VEHICULO" MODIFY ("ID_VEHICULO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CONDUCTOR_VEHICULO" MODIFY ("ID_CONDUCTOR" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."CONDUCTOR_VEHICULO" MODIFY ("ID_CONDUCTORVEHICULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DATALLE_METODO_DE_PAGO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."DATALLE_METODO_DE_PAGO" ADD CONSTRAINT "DATALLE_METODO_DE_PAGO_PK" PRIMARY KEY ("ID_DETALLEMETODOPAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."DATALLE_METODO_DE_PAGO" MODIFY ("FECHAVENCIMIENTOTARJETA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DATALLE_METODO_DE_PAGO" MODIFY ("CODIGOSEGURIDADTARJETA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DATALLE_METODO_DE_PAGO" MODIFY ("NUMEROTARJETA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DATALLE_METODO_DE_PAGO" MODIFY ("TIPOMEDIOPAGO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DATALLE_METODO_DE_PAGO" MODIFY ("ID_METODOPAGO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DATALLE_METODO_DE_PAGO" MODIFY ("ID_DETALLEMETODOPAGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLE_CODIGO_PROMOCIONAL
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."DETALLE_CODIGO_PROMOCIONAL" ADD CONSTRAINT "DETALLE_CODIGO_PROMOCIONAL_PK" PRIMARY KEY ("ID_DETALLECODIGOPROMOCIONAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."DETALLE_CODIGO_PROMOCIONAL" MODIFY ("FECHAREDENCION" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_CODIGO_PROMOCIONAL" MODIFY ("ESTADOCODIGO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_CODIGO_PROMOCIONAL" MODIFY ("VALOR_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_CODIGO_PROMOCIONAL" MODIFY ("ID_CODIGOPROMOCIONAL" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_CODIGO_PROMOCIONAL" MODIFY ("ID_DETALLECODIGOPROMOCIONAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLE_FACTURA
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."DETALLE_FACTURA" ADD CONSTRAINT "ID_DETALLEFACTURA_PK" PRIMARY KEY ("ID_DETALLEFACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."DETALLE_FACTURA" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_FACTURA" MODIFY ("DETALLE_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_FACTURA" MODIFY ("ID_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_FACTURA" MODIFY ("ID_DETALLEFACTURA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLE_RECORRIDO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."DETALLE_RECORRIDO" MODIFY ("ID_DETALLE_SERVICIO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_RECORRIDO" ADD CONSTRAINT "ID_DETALLERECORRIDO_PK" PRIMARY KEY ("ID_DETALLERECORRIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."DETALLE_RECORRIDO" MODIFY ("FECHA_HORA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_RECORRIDO" MODIFY ("LATITUD" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_RECORRIDO" MODIFY ("LONGITUD" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_RECORRIDO" MODIFY ("ID_DETALLERECORRIDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLE_SERVICIO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."DETALLE_SERVICIO" MODIFY ("ID_SERVICIO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_SERVICIO" ADD CONSTRAINT "ID_DETALLESERVICIO_PK" PRIMARY KEY ("ID_DETALLESERVICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."DETALLE_SERVICIO" MODIFY ("RECORRIDO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_SERVICIO" MODIFY ("TIEMPOTOTAL" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_SERVICIO" MODIFY ("MEDIOPAGO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_SERVICIO" MODIFY ("TIPO_TARIFA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_SERVICIO" MODIFY ("ID_DETALLESERVICIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLE_VEHICULO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."DETALLE_VEHICULO" ADD CONSTRAINT "ID_DETALLEVEHICULO_PK" PRIMARY KEY ("ID_DETALLEVEHICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."DETALLE_VEHICULO" MODIFY ("ID_VEHICULO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."DETALLE_VEHICULO" MODIFY ("ID_DETALLEVEHICULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENTIDAD_DE_PAGO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."ENTIDAD_DE_PAGO" ADD CONSTRAINT "ID_ENTIDADPAGO_PK" PRIMARY KEY ("ID_ENTIDADPAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."ENTIDAD_DE_PAGO" MODIFY ("DESCRIPCIONENTIDADPAGO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."ENTIDAD_DE_PAGO" MODIFY ("ID_ENTIDADPAGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADO_DE_SERVICIO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."ESTADO_DE_SERVICIO" ADD CONSTRAINT "ID_ESTADOSERVICIO_PK" PRIMARY KEY ("ID_ESTADOSERVICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."ESTADO_DE_SERVICIO" MODIFY ("DESCRIPCIONESTADOSERVICIO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."ESTADO_DE_SERVICIO" MODIFY ("ID_ESTADOSERVICIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FACTURA
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."FACTURA" ADD CONSTRAINT "ID_FACTURA_PK" PRIMARY KEY ("ID_FACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."FACTURA" MODIFY ("ID_FACTURA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GEOGRAFIA
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."GEOGRAFIA" ADD CONSTRAINT "GEOGRAFIA_PK" PRIMARY KEY ("ID_GEOGRAFIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."GEOGRAFIA" MODIFY ("CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."GEOGRAFIA" MODIFY ("PAIS" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."GEOGRAFIA" MODIFY ("DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."GEOGRAFIA" MODIFY ("ID_GEOGRAFIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LENGUAJE
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."LENGUAJE" ADD CONSTRAINT "LENGUAJE_PK" PRIMARY KEY ("ID_LENGUAJE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."LENGUAJE" MODIFY ("DESCRIPCION_LENGUAJE" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."LENGUAJE" MODIFY ("ID_LENGUAJE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LIQUIDACION
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."LIQUIDACION" ADD CONSTRAINT "ID_LIQUIDACION_PK" PRIMARY KEY ("ID_LIQUIDACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."LIQUIDACION" MODIFY ("ID_LIQUIDACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MARCA
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."MARCA" ADD CONSTRAINT "MARCA_PK" PRIMARY KEY ("ID_MARCA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."MARCA" MODIFY ("ID_MODELO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."MARCA" MODIFY ("DESCRIPCIONMARCA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."MARCA" MODIFY ("ID_MARCA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table METODO_DE_PAGO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."METODO_DE_PAGO" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."METODO_DE_PAGO" MODIFY ("ID_TIPO_MEDIO_DE_PAGO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."METODO_DE_PAGO" ADD CONSTRAINT "METODO_DE_PAGO_PK" PRIMARY KEY ("ID_METODOPAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."METODO_DE_PAGO" MODIFY ("DESCRIPCIONMETODOPAGO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."METODO_DE_PAGO" MODIFY ("ID_METODOPAGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MODELO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."MODELO" ADD CONSTRAINT "MODELO_PK" PRIMARY KEY ("ID_MODELO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."MODELO" MODIFY ("ID_AÑO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."MODELO" MODIFY ("DESCRIPCIONMODELO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."MODELO" MODIFY ("ID_MODELO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MONEDA
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."MONEDA" ADD CONSTRAINT "MONEDA_PK" PRIMARY KEY ("ID_MONEDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."MONEDA" MODIFY ("ID_GEOGRAFIA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."MONEDA" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."MONEDA" MODIFY ("DESCRIPCION_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."MONEDA" MODIFY ("ID_MONEDA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPORTE_PAGO_DETALLE
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."REPORTE_PAGO_DETALLE" ADD CONSTRAINT "ID_REPORTEPAGODETALLE_PK" PRIMARY KEY ("ID_REPORTEPAGODETALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."REPORTE_PAGO_DETALLE" MODIFY ("DESCRIPCIONPAGO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."REPORTE_PAGO_DETALLE" MODIFY ("VALORPAGO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."REPORTE_PAGO_DETALLE" MODIFY ("FECHAPAGO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."REPORTE_PAGO_DETALLE" MODIFY ("ID_ENTIDADPAGO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."REPORTE_PAGO_DETALLE" MODIFY ("ID_REPORTEPAGODETALLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICIO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."SERVICIO" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."SERVICIO" ADD CONSTRAINT "ID_SERVICIO_PK" PRIMARY KEY ("ID_SERVICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."SERVICIO" MODIFY ("ID_ESTADOSERVICIO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."SERVICIO" MODIFY ("ID_GEOGRAFIA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."SERVICIO" MODIFY ("ID_CONDUCTORVEHICULO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."SERVICIO" MODIFY ("FECHASERVICIO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."SERVICIO" MODIFY ("ID_SERVICIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_DOCUMENTO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."TIPO_DOCUMENTO" ADD CONSTRAINT "TIPO_DOCUMENTO_PK" PRIMARY KEY ("ID_TIPODOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."TIPO_DOCUMENTO" MODIFY ("DESCRIPCIONDOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."TIPO_DOCUMENTO" MODIFY ("ID_TIPODOCUMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_MEDIO_DE_PAGO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."TIPO_MEDIO_DE_PAGO" ADD CONSTRAINT "TIPO_MEDIO_DE_PAGO_PK" PRIMARY KEY ("ID_TIPO_MEDIO_DE_PAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."TIPO_MEDIO_DE_PAGO" MODIFY ("DESCRIPCION_TIPO_MEDIO_DE_PAGO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."TIPO_MEDIO_DE_PAGO" MODIFY ("ID_TIPO_MEDIO_DE_PAGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_VEHICULO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."TIPO_VEHICULO" ADD CONSTRAINT "TIPO_VEHICULO_PK" PRIMARY KEY ("ID_TIPOVEHICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."TIPO_VEHICULO" MODIFY ("DESCRIPCIONTIPOVEHICULO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."TIPO_VEHICULO" MODIFY ("ID_TIPOVEHICULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEHICULO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."VEHICULO" ADD CONSTRAINT "VEHICULO_PK" PRIMARY KEY ("ID_VEHICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "UBER"  ENABLE;
  ALTER TABLE "UBERDBA"."VEHICULO" MODIFY ("DESCRIPCIONVEHICULO" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."VEHICULO" MODIFY ("ID_MARCA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."VEHICULO" MODIFY ("PLACA" NOT NULL ENABLE);
  ALTER TABLE "UBERDBA"."VEHICULO" MODIFY ("ID_VEHICULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."CLIENTE" ADD CONSTRAINT "FK_ID_GEOGRAFIA" FOREIGN KEY ("ID_GEOGRAFIA")
	  REFERENCES "UBERDBA"."GEOGRAFIA" ("ID_GEOGRAFIA") ENABLE;
  ALTER TABLE "UBERDBA"."CLIENTE" ADD CONSTRAINT "FK_ID_LENGUAJE" FOREIGN KEY ("ID_LENGUAJE")
	  REFERENCES "UBERDBA"."LENGUAJE" ("ID_LENGUAJE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CODIGO_PROMOCIONAL
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."CODIGO_PROMOCIONAL" ADD CONSTRAINT "FK_ID_CLIENTE" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "UBERDBA"."CLIENTE" ("ID_CLIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONDUCTOR
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."CONDUCTOR" ADD CONSTRAINT "FK_ID_GEOGRAFIA_CONDUCTOR" FOREIGN KEY ("ID_GEOGRAFIA")
	  REFERENCES "UBERDBA"."GEOGRAFIA" ("ID_GEOGRAFIA") ENABLE;
  ALTER TABLE "UBERDBA"."CONDUCTOR" ADD CONSTRAINT "FK_ID_LENGUAJE_CONDUCTOR" FOREIGN KEY ("ID_LENGUAJE")
	  REFERENCES "UBERDBA"."LENGUAJE" ("ID_LENGUAJE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONDUCTOR_VEHICULO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."CONDUCTOR_VEHICULO" ADD CONSTRAINT "FK_ID_CONDUCTOR_CONDUCTOR" FOREIGN KEY ("ID_CONDUCTOR")
	  REFERENCES "UBERDBA"."CONDUCTOR" ("ID_CONDUCTOR") ENABLE;
  ALTER TABLE "UBERDBA"."CONDUCTOR_VEHICULO" ADD CONSTRAINT "FK_ID_VEHICULO_CONDUCTOR" FOREIGN KEY ("ID_VEHICULO")
	  REFERENCES "UBERDBA"."VEHICULO" ("ID_VEHICULO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_FACTURA
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."DETALLE_FACTURA" ADD CONSTRAINT "FK_ID_FACTURA" FOREIGN KEY ("ID_FACTURA")
	  REFERENCES "UBERDBA"."FACTURA" ("ID_FACTURA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_RECORRIDO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."DETALLE_RECORRIDO" ADD CONSTRAINT "FK_ID_DETALLE_SERVICIO" FOREIGN KEY ("ID_DETALLE_SERVICIO")
	  REFERENCES "UBERDBA"."SERVICIO" ("ID_SERVICIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_SERVICIO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."DETALLE_SERVICIO" ADD CONSTRAINT "FK_ID_SERVICIO" FOREIGN KEY ("ID_SERVICIO")
	  REFERENCES "UBERDBA"."SERVICIO" ("ID_SERVICIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_VEHICULO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."DETALLE_VEHICULO" ADD CONSTRAINT "FK_ID_VEHICULO" FOREIGN KEY ("ID_VEHICULO")
	  REFERENCES "UBERDBA"."VEHICULO" ("ID_VEHICULO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MARCA
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."MARCA" ADD CONSTRAINT "FK_ID_MODELO" FOREIGN KEY ("ID_MODELO")
	  REFERENCES "UBERDBA"."MODELO" ("ID_MODELO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table METODO_DE_PAGO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."METODO_DE_PAGO" ADD CONSTRAINT "FK_ID_CLIENTE_METODO_PAGO" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "UBERDBA"."CLIENTE" ("ID_CLIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MODELO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."MODELO" ADD CONSTRAINT "FK_ID_AÑO" FOREIGN KEY ("ID_AÑO")
	  REFERENCES "UBERDBA"."AÑO" ("ID_AÑO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MONEDA
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."MONEDA" ADD CONSTRAINT "FK_ID_GEOGRAFIA_MONEDA" FOREIGN KEY ("ID_GEOGRAFIA")
	  REFERENCES "UBERDBA"."GEOGRAFIA" ("ID_GEOGRAFIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORTE_PAGO_DETALLE
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."REPORTE_PAGO_DETALLE" ADD CONSTRAINT "FK_ID_ENTIDADPAGO" FOREIGN KEY ("ID_ENTIDADPAGO")
	  REFERENCES "UBERDBA"."ENTIDAD_DE_PAGO" ("ID_ENTIDADPAGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICIO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."SERVICIO" ADD CONSTRAINT "FK_ID_CLIETE_SERVICIO" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "UBERDBA"."CLIENTE" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "UBERDBA"."SERVICIO" ADD CONSTRAINT "FK_ID_CONDUCTOR_VEHICULO" FOREIGN KEY ("ID_CONDUCTORVEHICULO")
	  REFERENCES "UBERDBA"."CONDUCTOR_VEHICULO" ("ID_CONDUCTORVEHICULO") ENABLE;
  ALTER TABLE "UBERDBA"."SERVICIO" ADD CONSTRAINT "FK_ID_ESTADOSERVICIO" FOREIGN KEY ("ID_ESTADOSERVICIO")
	  REFERENCES "UBERDBA"."ESTADO_DE_SERVICIO" ("ID_ESTADOSERVICIO") ENABLE;
  ALTER TABLE "UBERDBA"."SERVICIO" ADD CONSTRAINT "FK_ID_GEOGRAFIA_SERVICIO" FOREIGN KEY ("ID_GEOGRAFIA")
	  REFERENCES "UBERDBA"."GEOGRAFIA" ("ID_GEOGRAFIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VEHICULO
--------------------------------------------------------

  ALTER TABLE "UBERDBA"."VEHICULO" ADD CONSTRAINT "FK_ID_MARCA" FOREIGN KEY ("ID_MARCA")
	  REFERENCES "UBERDBA"."MARCA" ("ID_MARCA") ENABLE;
  ALTER TABLE "UBERDBA"."VEHICULO" ADD CONSTRAINT "FK_ID_TIPO_VEHICULO" FOREIGN KEY ("ID_TIPO_VEHICULO")
	  REFERENCES "UBERDBA"."TIPO_VEHICULO" ("ID_TIPOVEHICULO") ENABLE;
